name: Container_Build_Push

on:
  push:
    branches:
      - container_release

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_SECRET }}

    - name: 'Docker Build & Push'
      run: |
        docker build frontend/ -t frontend_build --target build
        docker build backend/ -t ${{ secrets.REGISTRY_SERVER }}/tuturno:latest --target prod
        docker push ${{ secrets.REGISTRY_SERVER }}/tuturno:latest
